/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agent/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /` — every agent session in the workspace (`agent.list`). */
        get: operations["list_sessions"];
        put?: never;
        /**
         * `POST /` — record a new agent session (`agent.spawn`). Emits `agent.spawned.v1`. A re-spawn of
         *     an id already in the registry is a `422` (mirrors the MCP duplicate check). `201` on success.
         */
        post: operations["spawn_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /:id` — one session's state (`agent.info`); `404` when no session matches. */
        get: operations["get_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/{id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:id/end` — record a session's normal end (`agent.end`). Emits `agent.session-end.v1`,
         *     folding the session to `done`. `404` on an unknown id.
         */
        post: operations["end_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/{id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:id/heartbeat` — record a liveness heartbeat (`agent.heartbeat`). Emits
         *     `agent.heartbeat.v1`; a no-op on the registry but accepted + logged. `404` on an unknown id.
         */
        post: operations["heartbeat_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/{id}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:id/kill` — record a session forcibly killed with a reason (`agent.kill`). Emits
         *     `agent.killed.v1`, folding the session to `killed`. `404` on an unknown id; a missing `reason`
         *     is a `422`.
         */
        post: operations["kill_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /?owner_type&owner_id` — the live documents attached to an owner bead, newest first
         *     (`documents.list.execute`).
         */
        get: operations["list_documents"];
        put?: never;
        /**
         * `POST /` — attach a document to a bead (`documents.attach.execute`). The id is minted
         *     server-side (a ULID); `created_by` rides in the body (the agent's attribution, as on the MCP
         *     path). `201` on success with the stored document.
         */
        post: operations["attach_document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /search?query&owner_type&owner_id&limit` — hybrid (text + vector) search when an embedder
         *     is wired, else phase-1 full-text (`documents.search.execute`). An embed failure degrades to
         *     full-text rather than erroring, exactly as the MCP path does.
         */
        get: operations["search_documents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /:id` — one document with its body/extracted text + `version`; `404` when no live row
         *     matches (`gt://doc/{id}` read).
         */
        get: operations["get_document"];
        put?: never;
        post?: never;
        /**
         * `DELETE /:id?expected_version` — soft-delete a document under its version guard
         *     (`documents.remove.execute`). The id is the path; `expected_version` is the querystring (a
         *     DELETE carries no body). `200` echoes the removed id.
         */
        delete: operations["remove_document"];
        options?: never;
        head?: never;
        /**
         * `PATCH /:id` — edit a document under its optimistic version guard (`documents.update.execute`).
         *     The id always comes from the path and overwrites any `id` in the body (docs/03 Rule 6).
         *     Returns the post-bump document so a follow-up edit can chain `expected_version`.
         */
        patch: operations["update_document"];
        trace?: never;
    };
    "/api/v1/issues/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /` — a paged snapshot of the tracker (`gt://issues`). Reuses
         *     [`read_issues_page`](crate::resources::read_issues_page) so the page semantics match the MCP
         *     resource exactly.
         */
        get: operations["list_issues"];
        put?: never;
        /**
         * `POST /` — create a bead (`issues.create.execute`). The id lives in the body (it names the
         *     new resource, not an existing path), uniqueness is enforced by the store. `201` on success.
         */
        post: operations["create_issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /:id` — one issue with its heavy bodies + `version` (`gt://issue/{id}`); `404` when no
         *     row matches.
         */
        get: operations["get_issue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * `PATCH /:id` — patch editable fields (`issues.update.execute`). The id always comes from the
         *     path and overwrites any `id` in the body (docs/03 Rule 6: identity is never trusted from the
         *     payload). Returns the post-bump `version` so a follow-up edit can chain `expected_version`.
         */
        patch: operations["update_issue"];
        trace?: never;
    };
    "/api/v1/issues/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:id/claim` — atomically claim an open, unowned bead for the server actor
         *     (`issues.claim.execute`). A lost claim is a `409 Conflict` naming the current holder, so the
         *     caller cannot proceed as if it owns the bead; a win echoes the post-bump `version` and the
         *     S5 prose/phase fields.
         */
        post: operations["claim_issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:id/close` — close the bead (`issues.close.execute`). The attribution actor is the
         *     server identity in [`IssuesApiState`], never the body. A bead with a non-planned code
         *     surface still requires `commit_sha` (delivered-code proof), enforced by the shared handler;
         *     the git delivery verification (S2) is skipped on the REST path (see the module docs).
         */
        post: operations["close_issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:id/transition` — move the status across the open/working/closed machine
         *     (`issues.transition.execute`). Illegal moves are rejected by the store's status-guarded
         *     update and surface as `422`.
         */
        post: operations["transition_issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merge/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /` — every slot on the caller's merge board (`merge.list`). */
        get: operations["list_merges"];
        put?: never;
        /**
         * `POST /` — submit a bead's branch into the queue (`merge.submit`). The bead lives in the body
         *     (it names the new slot, like the issues `create` / rig `add`); a duplicate submit is rejected
         *     against the rehydrated board. `201` on success.
         */
        post: operations["submit_merge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merge/{bead}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /:bead` — one bead's merge slot (`merge.info`); `404` when no slot matches. */
        get: operations["get_merge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merge/{bead}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:bead/complete` — the edge reports a landed merge, `Merging → Merged` (`merge.complete`).
         *     The bead comes from the path; the landed `sha` lives in the body.
         */
        post: operations["complete_merge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merge/{bead}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:bead/fail` — the edge reports a failed merge, `Merging → Failed` (`merge.fail`). The
         *     bead comes from the path; the `reason` lives in the body.
         */
        post: operations["fail_merge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merge/{bead}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:bead/start` — take a queued slot to the physical merge, `Ready → Merging`
         *     (`merge.start`). The bead always comes from the path (docs/03 Rule 6).
         */
        post: operations["start_merge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/help": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /help` — the server's `tools/list` payload (`meta.help.execute`): every
         *     dispatchable tool with its description + input schema. A pure read, no state
         *     change. The shape matches the MCP `meta.help` result exactly.
         */
        get: operations["help"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/report-gap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /report-gap` — surface a missing operation (`meta.report-gap.execute`):
         *     the server mints a `hq-gap-<slug>-<ts>` bead so the gap enters the routine
         *     catalog. The attribution actor is the server identity in [`MetaApiState`], never
         *     the body. `201` on success, echoing the minted bead summary.
         */
        post: operations["report_gap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quota/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /` — every tracked account with its usage (`quota.list`). Reuses the replayed registry
         *     so the projection matches the MCP read exactly.
         */
        get: operations["list_accounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quota/{account}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /:account` — one account's usage + window (`quota.info`); `404` when no account matches. */
        get: operations["get_account"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quota/{account}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:account/probe` — reconcile the live window against provider remaining/reset
         *     (`quota.probe`). The account comes from the path. Emits `quota.usage_probed.v1`.
         */
        post: operations["probe_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quota/{account}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:account/rotate` — rotate active usage off this account onto another (`quota.rotate`),
         *     parking the source in cooldown. The path account is the `from_account` (the one rotated away
         *     from, docs/03 Rule 6); `to_account` is the healthy target in the body. A rotation onto itself
         *     is a `422`. Emits `quota.rotated.v1`.
         */
        post: operations["rotate_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quota/{account}/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:account/sample` — record a token-usage sample (`quota.sample`). The account always
         *     comes from the path and overwrites any `account` in the body (docs/03 Rule 6); the rest of
         *     the body (`session`/`model`/usage counters) is the sample. Emits `quota.tokens_sampled.v1`.
         */
        post: operations["sample_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rig/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /` — every rig in the caller's catalog (`rig.list`). */
        get: operations["list_rigs"];
        put?: never;
        /**
         * `POST /` — register a new rig (`rig.add`). The name lives in the body (it names the new
         *     resource, like the issues `create`), uniqueness enforced by the catalog. `201` on success.
         */
        post: operations["add_rig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rig/adopt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /adopt` — adopt an existing on-disk rig into the catalog (`rig.adopt`). Same shape as
         *     `POST /`; emits the distinct `rig.adopted` kind. `201` on success.
         */
        post: operations["adopt_rig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rig/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /lookup?prefix=` — resolve the rig owning a given bead-id prefix (`rig.lookup-by-prefix`).
         * @description A static segment, so it never shadows `GET /:name` (axum routes static before dynamic). `404`
         *     when no rig in the workspace owns the prefix.
         */
        get: operations["lookup_by_prefix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rig/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /:name` — one rig's catalog entry (`rig.info`); `404` when no rig matches. */
        get: operations["get_rig"];
        put?: never;
        post?: never;
        /**
         * `DELETE /:name` — drop a rig from the catalog (`rig.remove`). The name comes from the path;
         *     the command decides against the live catalog (rejecting an absent rig as `404`) before the
         *     row is deleted.
         */
        delete: operations["remove_rig"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rig/{name}/set-default-branch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /:name/set-default-branch` — change a rig's default branch (`rig.set-default-branch`). */
        post: operations["set_default_branch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rig/{name}/set-prefix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:name/set-prefix` — change a rig's bead-id prefix (`rig.set-prefix`). The name always
         *     comes from the path and overwrites any `name` in the body (docs/03 Rule 6).
         */
        post: operations["set_prefix"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rig/{name}/set-worktree-root": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /:name/set-worktree-root` — pin a rig's worktree-root override (`rig.set-worktree-root`). */
        post: operations["set_worktree_root"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /` — every workspace in the catalog (`workspace.list`). A pure read straight
         *     off the repository; the envelope matches the MCP tool's `{ "workspaces": [...] }`.
         */
        get: operations["list_workspaces"];
        put?: never;
        /**
         * `POST /` — provision a new active workspace in the catalog (`workspace.create`).
         *     The id lives in the body (it names the new resource), uniqueness is enforced by
         *     the decide layer (`409` on a duplicate). Runs the full [`WorkspaceActor`] cycle so
         *     the change is a replayable event. `201` on success.
         */
        post: operations["create_workspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /:id` — one workspace's id, name + status (`workspace.info`); `404` when the
         *     catalog holds no such id.
         */
        get: operations["get_workspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:id/archive` — archive a workspace (`workspace.archive`, terminal). The
         *     decide layer rejects an already-archived workspace as an illegal transition (`409`).
         */
        post: operations["archive_workspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:id/resume` — restore a suspended workspace to active (`workspace.resume`).
         *     The decide layer rejects a non-suspended source as an illegal transition (`409`).
         */
        post: operations["resume_workspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/{id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /:id/suspend` — reversibly disable an active workspace (`workspace.suspend`).
         *     The decide layer rejects a non-active source as an illegal transition (`409`).
         */
        post: operations["suspend_workspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every agent session in the workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    spawn_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session spawned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A session with that id already exists */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session's state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    end_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    heartbeat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Heartbeat recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    kill_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session killed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing kill reason */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_documents: {
        parameters: {
            query: {
                /** @description Owning bead class (epic|skill|spec) */
                owner_type: string;
                /** @description Owning bead id */
                owner_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documents for the owner */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    attach_document: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document attached */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (shape / bad base64) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No object store configured for a blob attach, or a store error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_documents: {
        parameters: {
            query: {
                /** @description Free-text query (websearch syntax) */
                query: string;
                /** @description Optional owner narrowing (paired with owner_id) */
                owner_type?: string;
                /** @description Optional owner narrowing (paired with owner_type) */
                owner_id?: string;
                /** @description Max hits (default 20) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked document hits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No document with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_document: {
        parameters: {
            query: {
                /** @description The version the caller last read */
                expected_version: number;
            };
            header?: never;
            path: {
                /** @description Document id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document soft-deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No document with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version conflict (stale expected_version) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patched; returns the post-bump document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No document with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version conflict (stale expected_version) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_issues: {
        parameters: {
            query?: {
                /** @description Comma-separated status filter */
                status?: string;
                /** @description Keep priority <= this */
                priority_max?: number;
                /** @description Exact assignee match */
                assignee?: string;
                /** @description Exact external_ref (epic) match */
                external_ref?: string;
                /** @description Exact issue_type match */
                issue_type?: string;
                /** @description Page size */
                limit?: number;
                /** @description Zero-based row offset */
                offset?: number;
                /** @description Inline heavy text bodies */
                full?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of issues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_issue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (shape / NN-16 taxonomy) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_issue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bead id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The issue with heavy bodies + version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No issue with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_issue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bead id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patched; returns the post-bump version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (incl. version conflict) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    claim_issue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bead id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claim won; echoes version + S5 fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No issue with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already claimed by another holder */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    close_issue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bead id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No issue with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (e.g. missing commit_sha for a code surface) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    transition_issue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bead id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status transitioned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Illegal or invalid transition */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_merges: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every slot on the workspace merge board */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submit_merge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merge slot registered in Ready */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (empty fields or already submitted) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_merge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bead id */
                bead: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bead's merge slot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No merge slot for that bead */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    complete_merge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bead id */
                bead: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Slot moved to Merged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No merge slot for that bead */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Illegal transition (not in Merging) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (missing sha) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    fail_merge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bead id */
                bead: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Slot moved to Failed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No merge slot for that bead */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Illegal transition (not in Merging) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (missing reason) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_merge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bead id */
                bead: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Slot moved to Merging */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No merge slot for that bead */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Illegal transition (not in Ready) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    help: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The full tools/list (names, descriptions, input schemas) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    report_gap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gap bead minted; echoes { bead, operation, priority, external_ref } */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (e.g. empty operation) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_accounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every tracked account with its usage + window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account id */
                account: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account's usage + window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No account with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    probe_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account id */
                account: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Window reconciled; echoes the emitted event kind */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rotate_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account rotated away from (from_account) */
                account: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotated; echoes the emitted event kind */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (empty or self-rotation) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sample_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account id */
                account: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sample recorded; echoes the emitted event kind */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (empty session/model) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_rigs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every rig in the workspace catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_rig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rig registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (name/prefix grammar or collision) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adopt_rig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rig adopted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (name/prefix grammar or collision) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    lookup_by_prefix: {
        parameters: {
            query: {
                /** @description Bead-id prefix to resolve */
                prefix: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rig owning the prefix */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No rig owns that prefix in this workspace */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_rig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rig name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rig's catalog entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No rig with that name */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_rig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rig name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rig removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No rig with that name */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_default_branch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rig name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default branch changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No rig with that name */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (empty or no-op) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_prefix: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rig name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prefix changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No rig with that name */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (grammar, collision, or no-op) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_worktree_root: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rig name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Worktree root pinned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No rig with that name */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (relative path, `..`, too long, or no-op) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_workspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every workspace in the catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A workspace with that id already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid id or blank name */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace slug */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace's id, name + status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No workspace with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    archive_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace slug */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No workspace with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already archived (illegal transition) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resume_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace slug */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No workspace with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not suspended (illegal transition) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    suspend_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace slug */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace suspended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No workspace with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not active (illegal transition) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
